
module.exports = Object.assign(
	require('./ContainerWrapper.js'),
	require('./DataClassWrapper.js'),
	require('./DataPropertyWrapper.js'),
	require('./ElementWrapper.js'),
	require('./ElementFactory.js'),
	require('./View.js'),
	require('./Anchor.js'),
	require('./AnchorCss.js'),
	require('./AnchorCssBootStrap.js'),
	require('./Button.js'),
	require('./Input.js'),
	require('./InputCss.js'),
	require('./InputCssBootStrap.js'),
	require('./InputCssW3.js'),
	require('./InputValidator.js'),
	require('./Formatter.js'),
	require('./TextArea.js'),
	require('./Select.js'),
	require('./Span.js'),
	require('./Table.js'),
	require('./TableCss.js'),
	require('./TableCssBootStrap.js'),
	require('./TableCssW3.js'),
	require('./Th.js'),
	require('./CssDelegate.js'),
);